### ISSUE TITLE
[Request] Info on adding certs to keystore/truststore

### ISSUE THREAD

**Issue by bzlister** [AlphaGarden/SSL-Client-Server#1]
Is there any way you could show the commands used to add the .p12 certs to keystores and truststores? I've been having a lot of difficulty with it.

**Comment by AlphaGarden** [comment]
Please place those files under client and server folders if you work on a maven project and make sure they follow the below structure:
\- src
 -- main
   --- java
   --- resources
     ---- client
     ---- server
Hope this helps.
